### ISSUE TITLE
Identify fields from GitHub Issue for mapping with ERPNext's Task DocType

### ISSUE THREAD

**Issue by gaurav-naik** [gaurav-naik/gi2et#2]

**Comment by revant** [comment]
**task = issue**
subject = title
status = state
exp_start_date = created_at
exp_end_date =
description = body
closing_date  = closed_at

add custom field in Task to map : 
github_id = "id" and 
github_number = "number"

<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 5%">Sr</th>
            <th style="width: 25%">Fieldname</th>
            <th style="width: 20%">Type</th>
            <th style="width: 25%">Label</th>
            <th style="width: 25%">Options</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td>1</td>
            <td class="danger" title="Mandatory"><code>subject</code></td>
            <td>
                Data</td>
            <td>
                Subject
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>2</td>
            <td><code>project</code></td>
            <td>
                Link</td>
            <td>
                Project
                
            </td>
            <td>
                
                
<a href="https://frappe.github.io/erpnext/current/models/projects/project">Project</a>
                
            </td>
        </tr>
        
        <tr>
            <td>3</td>
            <td><code>column_break0</code></td>
            <td class="info">
                Column Break</td>
            <td>
                
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>4</td>
            <td><code>status</code></td>
            <td>
                Select</td>
            <td>
                Status
                
            </td>
            <td>
                <pre>Open
Working
Pending Review
Overdue
Closed
Cancelled</pre>
            </td>
        </tr>
        
        <tr>
            <td>5</td>
            <td><code>priority</code></td>
            <td>
                Select</td>
            <td>
                Priority
                
            </td>
            <td>
                <pre>Low
Medium
High
Urgent</pre>
            </td>
        </tr>
        
        <tr class="info">
            <td>6</td>
            <td><code>section_break_10</code></td>
            <td>
                Section Break</td>
            <td>
                
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>7</td>
            <td><code>exp_start_date</code></td>
            <td>
                Date</td>
            <td>
                Expected Start Date
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>8</td>
            <td><code>expected_time</code></td>
            <td>
                Float</td>
            <td>
                Expected Time (in hours)
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>9</td>
            <td><code>column_break_11</code></td>
            <td class="info">
                Column Break</td>
            <td>
                
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>10</td>
            <td><code>exp_end_date</code></td>
            <td>
                Date</td>
            <td>
                Expected End Date
                
            </td>
            <td></td>
        </tr>
        
        <tr class="info">
            <td>11</td>
            <td><code>section_break0</code></td>
            <td>
                Section Break</td>
            <td>
                
                
            </td>
            <td>
                <pre>Simple</pre>
            </td>
        </tr>
        
        <tr>
            <td>12</td>
            <td><code>description</code></td>
            <td>
                Text Editor</td>
            <td>
                Details
                
            </td>
            <td></td>
        </tr>
        
        <tr class="info">
            <td>13</td>
            <td><code>section_break</code></td>
            <td>
                Section Break</td>
            <td>
                Depends On
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>14</td>
            <td><code>depends_on</code></td>
            <td>
                Table</td>
            <td>
                depends_on
                
            </td>
            <td>
                
                
<a href="https://frappe.github.io/erpnext/current/models/projects/task_depends_on">Task Depends On</a>
                
            </td>
        </tr>
        
        <tr class="info">
            <td>15</td>
            <td><code>actual</code></td>
            <td>
                Section Break</td>
            <td>
                
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>16</td>
            <td><code>act_start_date</code></td>
            <td>
                Date</td>
            <td>
                Actual Start Date (via Time Logs)
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>17</td>
            <td><code>actual_time</code></td>
            <td>
                Float</td>
            <td>
                Actual Time (in hours)
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>18</td>
            <td><code>column_break_15</code></td>
            <td class="info">
                Column Break</td>
            <td>
                
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>19</td>
            <td><code>act_end_date</code></td>
            <td>
                Date</td>
            <td>
                Actual End Date (via Time Logs)
                
            </td>
            <td></td>
        </tr>
        
        <tr class="info">
            <td>20</td>
            <td><code>section_break_17</code></td>
            <td>
                Section Break</td>
            <td>
                
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>21</td>
            <td><code>total_costing_amount</code></td>
            <td>
                Currency</td>
            <td>
                Total Costing Amount (via Time Logs)
                
            </td>
            <td>
                <pre>Company:company:default_currency</pre>
            </td>
        </tr>
        
        <tr>
            <td>22</td>
            <td><code>total_expense_claim</code></td>
            <td>
                Currency</td>
            <td>
                Total Expense Claim (via Expense Claim)
                
            </td>
            <td>
                <pre>Company:company:default_currency</pre>
            </td>
        </tr>
        
        <tr>
            <td>23</td>
            <td><code>column_break_20</code></td>
            <td class="info">
                Column Break</td>
            <td>
                
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>24</td>
            <td><code>total_billing_amount</code></td>
            <td>
                Currency</td>
            <td>
                Total Billing Amount (via Time Logs)
                
            </td>
            <td></td>
        </tr>
        
        <tr class="info">
            <td>25</td>
            <td><code>more_details</code></td>
            <td>
                Section Break</td>
            <td>
                
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>26</td>
            <td><code>review_date</code></td>
            <td>
                Date</td>
            <td>
                Review Date
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>27</td>
            <td><code>closing_date</code></td>
            <td>
                Date</td>
            <td>
                Closing Date
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>28</td>
            <td><code>column_break_22</code></td>
            <td class="info">
                Column Break</td>
            <td>
                
                
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td>29</td>
            <td><code>company</code></td>
            <td>
                Link</td>
            <td>
                Company
                
            </td>
            <td>
                
                
<a href="https://frappe.github.io/erpnext/current/models/setup/company">Company</a>
                
            </td>
        </tr>
        
    </tbody>
</table>
